// Generated by @arviahq/compiler - do not edit.

export type BadgeProps = {
  tone?: "neutral" | "primary" | "success" | "warning" | "danger";
  size?: "sm" | "md";
};

export type BadgeSlots = {
  root: string;
};

export declare function Badge(props?: BadgeProps): BadgeSlots;
