// Generated by @arviahq/compiler - do not edit.

export type BoxProps = {
  padding?: "none" | "1" | "2" | "3" | "4" | "5" | "6";
  radius?: "none" | "sm" | "md" | "lg" | "xl" | "full";
  background?: "transparent" | "surface" | "raised" | "muted";
};

export type BoxSlots = {
  root: string;
};

export declare function Box(props?: BoxProps): BoxSlots;
