// Generated by @arviahq/compiler - do not edit.

export type ButtonProps = {
  size?: "sm" | "md" | "lg";
  tone?: "primary" | "secondary" | "ghost" | "danger";
};

export type ButtonSlots = {
  root: string;
  icon: string;
  label: string;
};

export declare function Button(props?: ButtonProps): ButtonSlots;
