// Generated by @arviahq/compiler - do not edit.

export type CardProps = {
  padding?: "none" | "sm" | "md" | "lg";
  shadow?: "none" | "sm" | "md" | "lg";
};

export type CardSlots = {
  root: string;
};

export declare function Card(props?: CardProps): CardSlots;
