// Generated by @arviahq/compiler - do not edit.

export type DividerProps = {
  spacing?: "none" | "sm" | "md" | "lg";
};

export type DividerSlots = {
  root: string;
};

export declare function Divider(props?: DividerProps): DividerSlots;
