// Generated by @arviahq/compiler - do not edit.

export type HeadingProps = {
  level?: "1" | "2" | "3" | "4" | "5" | "6";
  tone?: "default" | "muted" | "primary";
};

export type HeadingSlots = {
  root: string;
};

export declare function Heading(props?: HeadingProps): HeadingSlots;
