// Generated by @arviahq/compiler - do not edit.

export type InputProps = {
  size?: "sm" | "md" | "lg";
};

export type InputSlots = {
  root: string;
};

export declare function Input(props?: InputProps): InputSlots;
