// Generated by @arviahq/compiler - do not edit.

export type LinkProps = {
  tone?: "primary" | "muted" | "danger";
  size?: "sm" | "md" | "lg";
};

export type LinkSlots = {
  root: string;
};

export declare function Link(props?: LinkProps): LinkSlots;
