// Generated by @arviahq/compiler - do not edit.

export type SpinnerProps = {
  size?: "sm" | "md" | "lg";
};

export type SpinnerSlots = {
  root: string;
};

export declare function Spinner(props?: SpinnerProps): SpinnerSlots;
