// Generated by @arviahq/compiler - do not edit.

export type StackProps = {
  direction?: "row" | "column";
  gap?: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8";
  align?: "start" | "center" | "end" | "stretch" | "baseline";
  justify?: "start" | "center" | "end" | "between" | "around";
  wrap?: "yes" | "no";
};

export type StackSlots = {
  root: string;
};

export declare function Stack(props?: StackProps): StackSlots;
