// Generated by @arviahq/compiler - do not edit.

export type TextProps = {
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  weight?: "regular" | "medium" | "semibold" | "bold";
  tone?: "default" | "muted" | "subtle" | "primary" | "danger" | "success";
};

export type TextSlots = {
  root: string;
};

export declare function Text(props?: TextProps): TextSlots;
