// Generated by @arviahq/compiler - do not edit.

export declare const divider: string;

export declare const tokens: {
  readonly color: {
    /** Brand primary — actions and emphasis */
    readonly primary: "var(--arvia-color-primary)";
    readonly primaryHover: "var(--arvia-color-primaryHover)";
    readonly primarySubtle: "var(--arvia-color-primarySubtle)";
    /** Secondary accent */
    readonly accent: "var(--arvia-color-accent)";
    /** Destructive actions */
    readonly danger: "var(--arvia-color-danger)";
    readonly dangerHover: "var(--arvia-color-dangerHover)";
    readonly dangerSubtle: "var(--arvia-color-dangerSubtle)";
    /** Positive feedback */
    readonly success: "var(--arvia-color-success)";
    readonly successSubtle: "var(--arvia-color-successSubtle)";
    /** Caution states */
    readonly warning: "var(--arvia-color-warning)";
    readonly warningSubtle: "var(--arvia-color-warningSubtle)";
    readonly text: "var(--arvia-color-text)";
    readonly muted: "var(--arvia-color-muted)";
    readonly subtle: "var(--arvia-color-subtle)";
    readonly surface: "var(--arvia-color-surface)";
    readonly surfaceRaised: "var(--arvia-color-surfaceRaised)";
    readonly background: "var(--arvia-color-background)";
    readonly border: "var(--arvia-color-border)";
    readonly borderStrong: "var(--arvia-color-borderStrong)";
    readonly focus: "var(--arvia-color-focus)";
  };
  readonly space: {
    readonly "1": "var(--arvia-space-1)";
    readonly "2": "var(--arvia-space-2)";
    readonly "3": "var(--arvia-space-3)";
    readonly "4": "var(--arvia-space-4)";
    readonly "5": "var(--arvia-space-5)";
    readonly "6": "var(--arvia-space-6)";
    readonly "7": "var(--arvia-space-7)";
    readonly "8": "var(--arvia-space-8)";
    readonly "9": "var(--arvia-space-9)";
  };
  readonly radius: {
    readonly sm: "var(--arvia-radius-sm)";
    readonly md: "var(--arvia-radius-md)";
    readonly lg: "var(--arvia-radius-lg)";
    readonly xl: "var(--arvia-radius-xl)";
    readonly full: "var(--arvia-radius-full)";
  };
  readonly font: {
    readonly xs: "var(--arvia-font-xs)";
    readonly sm: "var(--arvia-font-sm)";
    readonly md: "var(--arvia-font-md)";
    readonly lg: "var(--arvia-font-lg)";
    readonly xl: "var(--arvia-font-xl)";
    readonly "2xl": "var(--arvia-font-2xl)";
    readonly "3xl": "var(--arvia-font-3xl)";
    readonly "4xl": "var(--arvia-font-4xl)";
  };
  readonly shadow: {
    readonly sm: "var(--arvia-shadow-sm)";
    readonly md: "var(--arvia-shadow-md)";
    readonly lg: "var(--arvia-shadow-lg)";
  };
  readonly duration: {
    readonly fast: "var(--arvia-duration-fast)";
    readonly normal: "var(--arvia-duration-normal)";
    readonly slow: "var(--arvia-duration-slow)";
  };
  readonly easing: {
    readonly default: "var(--arvia-easing-default)";
    readonly out: "var(--arvia-easing-out)";
  };
};

export type ColorToken = keyof (typeof tokens)["color"];

export type SpaceToken = keyof (typeof tokens)["space"];

export type RadiusToken = keyof (typeof tokens)["radius"];

export type FontToken = keyof (typeof tokens)["font"];

export type ShadowToken = keyof (typeof tokens)["shadow"];

export type DurationToken = keyof (typeof tokens)["duration"];

export type EasingToken = keyof (typeof tokens)["easing"];
